// Code generated by xgen. DO NOT EDIT.

package musicxml

import (
	"encoding/xml"

	"github.com/sunmoondevlab/Go-MusicXml-Parser/musicxml"
)

func ParseMusicXml(mx string) musicxml.ScorePartwise{
	spw := musicxml.ScorePartwise{}
	_ = xml.Unmarshal([]byte(mx), &spw)
	return spw
}