// Code generated by xgen. DO NOT EDIT.

package musicxml

import (
	"encoding/xml"

	"github.com/sunmoondevlab/Go-MusicXml-Parser/musicxml/element"
)

func ParseMusicXml(mx string) element.ScorePartwise{
	spw := element.ScorePartwise{}
	_ = xml.Unmarshal([]byte(mx), &spw)
	return spw
}